### ISSUE TITLE
Panic despawning non-existent entity

### ISSUE THREAD

**Issue by keis** [viridia/quill#22]
I have setup using `For::each`, `Cond`, and a `Mutable` which can cause quill to get into trouble trying to despawn an entity.

```
2024-08-17T12:18:19.750435Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity Entity { index: 20, generation: 1 } because it doesn't exist in this World. See: https://bevyengine.org/learn/errors/#b0003
```

I've tried to create a reduced example but could probably be simplified more. Removing either the Cond or the update of the mutable stops the panic from happening. I was able to bisect the issue to be starting from 479fc2aedfd5646abf88aa1f1dec7ee018829813

- Run the example
- click the button
- panic

```
//! Example of a simple UI layout
#![feature(impl_trait_in_assoc_type)]

#[path = "./common/lib.rs"]
mod common;

use bevy::prelude::*;
use bevy_mod_picking::prelude::*;
use bevy_quill::{Cond, Cx, Element, For, Mutable, QuillPlugin, View, ViewTemplate};
use common::*;

fn main() {
    App::new()
        .add_plugins((
            DefaultPlugins.set(ImagePlugin::default_nearest()),
            QuillPlugin,
            DefaultPickingPlugins,
        ))
        .init_resource::<Birds>()
        .observe(Birds::on_add)
        .observe(Birds::on_remove)
        .add_systems(Startup, (setup, setup_view_root, setup_birds))
        .add_systems(Update, (close_on_esc, rotate))
        .run();
}

fn setup_view_root(mut commands: Commands) {
    commands.spawn(Reproduce.to_root());
}

fn setup_birds(mut commands: Commands) {
    commands.spawn(Bird);
}

#[derive(Component)]
struct Bird;

#[derive(Resource, Default)]
struct Birds(Vec<Entity>);

impl Birds {
    pub fn on_add(trigger: Trigger<OnAdd, Bird>, mut birds: ResMut<Self>) {
        birds.0.push(trigger.entity());
    }

    pub fn on_remove(trigger: Trigger<OnRemove, Bird>, mut birds: ResMut<Self>) {
        birds.0.retain(|&e| e != trigger.entity());
    }
}

#[derive(Clone, PartialEq)]
struct Reproduce;

impl ViewTemplate for Reproduce {
    type View = impl View;

    fn create(&self, cx: &mut Cx) -> Self::View {
        let selected = cx.create_mutable::<Option<Entity>>(None);
        let birds = cx.use_resource::<Birds>().0.clone();
        selected.update(cx, |mut selected: Mut<Option<Entity>>| {
            let new_selected = selected
                .filter(|s| birds.contains(s))
                .or(birds.first().copied());
            if new_selected != *selected {
                info!("Updating selected {:?}", new_selected);
                *selected = new_selected;
            }
        });
        Element::<NodeBundle>::new().children((
            For::each(birds, move |&item| SubComponent { item, selected }),
            Element::<ButtonBundle>::new()
                .insert_dyn(
                    move |_| {
                        On::<Pointer<Click>>::run(
                            move |mut commands: Commands, birds: Query<Entity, With<Bird>>| {
                                info!("Clicked");
                                for bird in &birds {
                                    commands.entity(bird).despawn();
                                }
                            },
                        )
                    },
                    (),
                )
                .children("Click me"),
        ))
    }
}

#[derive(Clone, PartialEq)]
struct SubComponent {
    pub item: Entity,
    pub selected: Mutable<Option<Entity>>,
}

impl ViewTemplate for SubComponent {
    type View = impl View;

    fn create(&self, cx: &mut Cx) -> Self::View {
        let selected = self.selected.get(cx);
        Cond::new(
            selected.is_some(),
            Element::<NodeBundle>::new().children("Bird"),
            (),
        )
    }
}
```

**Comment by viridia** [comment]
I'll try and see if I can find time to look at this in a day or two.

**Comment by keis** [comment]
Sprinkled some more info! calls under the verbose feature and managed to get this trace of the issue. Looks like quill ends up trying to raze() the same structure again in the second reaction iteration

```
2024-08-28T16:42:45.031141Z  INFO crash: Clicked
2024-08-28T16:42:45.031454Z  INFO bevy_quill_core::view: Reaction iteration: 0
2024-08-28T16:42:45.031474Z  INFO bevy_quill_core::view_template: rebuild()
2024-08-28T16:42:45.031489Z  INFO crash: Updating selected None
2024-08-28T16:42:45.031504Z  INFO bevy_quill_core::view_template: raze() 18v1
2024-08-28T16:42:45.031511Z  INFO bevy_quill_core::cond: raze()
2024-08-28T16:42:45.031516Z  INFO bevy_quill_core::element: Razing element: 19v1
2024-08-28T16:42:45.031521Z  INFO bevy_quill_core::text_view: Razing &str View: 20v1
2024-08-28T16:42:45.031757Z  INFO bevy_quill_core::view: Reaction iteration: 1
2024-08-28T16:42:45.031772Z  INFO bevy_quill_core::view_template: rebuild()
2024-08-28T16:42:45.031782Z  INFO bevy_quill_core::cond: rebuild()
2024-08-28T16:42:45.031786Z  INFO bevy_quill_core::cond: raze()
2024-08-28T16:42:45.031789Z  INFO bevy_quill_core::element: Razing element: 19v1
2024-08-28T16:42:45.031794Z  INFO bevy_quill_core::text_view: Razing &str View: 20v1
2024-08-28T16:42:45.031798Z  INFO bevy_quill_core::view: View output changed: 18v1
thread 'main' panicked at /home/keis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_hierarchy-0.14.0/src/child_builder.rs:251:15:
Entity Entity { index: 19, generation: 1 } does not exist
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_quill_core::view::reaction_control_system`!
2024-08-28T16:42:45.032141Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity Entity { index: 19, generation: 1 } because it doesn't exist in this World. See: https://bevyengine.org/learn/errors/#b0003
thread 'main' panicked at /home/keis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_hierarchy-0.14.0/src/child_builder.rs:251:15:
Entity Entity { index: 20, generation: 1 } does not exist
Encountered a panic in system `bevy_quill_core::view::reattach_children`!
2024-08-28T16:42:45.032234Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity Entity { index: 20, generation: 1 } because it doesn't exist in this World. See: https://bevyengine.org/learn/errors/#b0003
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

**Comment by viridia** [comment]
If only I could get some traction on https://github.com/bevyengine/bevy/issues/14826, I could remove raze() entirely.

**Comment by keis** [comment]
I remember fragments being a really useful construct in React for creating higher order components etc. I can see how it would be really help simplify quill as well.

No clue how intrusive that change is to bevy though, I'll throw a :+1: on the discussion in support though fwiw
